### ISSUE TITLE
IKS Script

### ISSUE THREAD

**Issue by odrodrig** [odrodrig/DevOpsWorkshop#12]
## Description
As a developer I need a script that will create a cluster in the IBM Kubernetes Service, so that I can run through the DevOps workshop on public kubernetes. 

## Acceptance Criterea
- [x] solution creates cluster
- [x] solution is documented in readme

## Depends On
odrodrig/DevOpsWorkshop#15

**Comment by mlangbehn** [comment]
So the [existing script](https://github.com/odrodrig/DevOpsWorkshop/blob/iks/scripts/createCluster.sh) works, but is not documented. Is the goal of this issue to simply document the existing script, or to make the script pretty first?

**Comment by mlangbehn** [comment]
This issue will be resolved when #17 is merged.
