### ISSUE TITLE
Jenkins install script

### ISSUE THREAD

**Issue by odrodrig** [odrodrig/DevOpsWorkshop#13]
## Description
As a developer, I need a script that installs jenkins into IKS so that I can easily create an externally accessible instance of Jenkins to use in the workshop.

## Acceptance Criterea
- [x] Solution installs Jenkins in IKS
- [x] Solution is documented in Readme

## Depends on
*   odrodrig/DevOpsWorkshop#12

**Comment by mlangbehn** [comment]
Should this be handled by the IKS [`createCluster.sh`](https://github.com/odrodrig/DevOpsWorkshop/blob/iks/scripts/createCluster.sh) script?

**Comment by odrodrig** [comment]
I think we decided to have this separate just in case someone wants to manually install Jenkins rather than have a script do it for you. 

Although now that I think about it, it doesn't seem like there would be that much more that you need to do manually. Might just be easier to have everybody use the script but explain exactly what the script is doing.

Might also be easiest to install Jenkins with a helm chart. 

What do you think would be easier?

**Comment by mlangbehn** [comment]
We could easily use helm, but we don't have to. It would be faster to just add the logic for specifying the cluster to use and kubectl applying the [jenkins.yaml](https://github.com/odrodrig/DevOpsWorkshop/blob/iks/kube/jenkins.yaml) file.

**Comment by odrodrig** [comment]
That's true. Let's forget about helm then.
