### ISSUE TITLE
Add testing scripts

### ISSUE THREAD

**Issue by odrodrig** [odrodrig/DevOpsWorkshop#18]
As a developer, I want to have automatic tests run on the code in this repo so that we can be sure that the latest changes work.

- [x] Integration with Travis CI
    - [x] Integration added to master branch
    - [x] Integration added to iks branch
    - [x] Integration added to icp branch
- [x] Travis CI build icon added to each branch's README
    - [x] master branch
    - [x] iks branch
    - [x] icp branch

**Comment by mlangbehn** [comment]
Running a quick `jslint` against the master branch fails with the following:

```shell
% find . -name '*.js' -print0 | xargs -0 jslint --color --node --indent                                                 add_travisci %

./nodeApp/tests/test.js
 #1 Unexpected 'let'.
    let chai = require('chai'); // Line 3, Pos 1
 #2 Stopping. (14% scanned).
     // Line 3, Pos 5
[1]    64587 done       find . -name '*.js' -print0 | 
       64588 exit 123   xargs -0 jslint --color --node --indent
```

**Comment by odrodrig** [comment]
@mlangbehn probably an old version of Node. I believe 'let' was a more recent addition to Node.js.

**Comment by mlangbehn** [comment]
https://travis-ci.org/mlangbehn/DevOpsWorkshop/builds/479529429

**Comment by mlangbehn** [comment]
I am going to open a pull request against master, and then cherry-pick the commit into the iks, and icp branches. After doing so, I plan on updating the Jenkinsfile (in each branch) to run all of the new tests, and adding the Travis CI build icon to each README.
